### ISSUE TITLE
Get statistics for 3 rounds

### ISSUE THREAD

**Issue by AlexDevsTheWeb** [AlexDevsTheWeb/personalgolfscore#50]
We must insert 3 rounds, and get JSON files for single round.
HOLES and TOTALS are the properties we need to calculate later the general statistics of all rounds

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified RoundSave component to save rounds and generate JSON files. Updated AddNewRoundHoles component to handle multiple rounds. Added new utility function to generate JSON files.

You can review changes in this commit: https://github.com/lattaai12/AlexDevsTheWeb-personalgolfscore-50/commit/d4ea6f1dad64aa212b6ffd175fcaa6afbcab5ee4.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
